name: WarcSearcher Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run unit tests with coverage
      run: |
        coverage run -m pytest tests/

    - name: Check coverage percentage
      run: |
        coverage report --fail-under=80

  file-operations:
    name: File Operations Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Set up test data
      run: |
        rm ./config.ini
        cp ./tests/test_data/test_config.ini ./config.ini
        test -f "./config.ini"

    - name: Run application
      run: |
        set -e
        python source/main.py

    - name: Verify output files
      run: |
        # Check if directories exist
        test -d "./tests/test_data/test_warc_gz_archives"
        test -d "./tests/test_data/test_regex_definitions"
        test -d "./tests/test_data/test_results_output"

        ls -lhR "./tests/test_data/test_results_output"

        test $(find "./tests/test_data/test_results_output" -name "log.log" | wc -l) -gt 0
        test $(find "./tests/test_data/test_results_output" -name "slamfest_results.txt" | wc -l) -gt 0
        test $(find "./tests/test_data/test_results_output" -name "slamfest_results.zip" | wc -l) -gt 0

        # Check file sizes
        txt_size_kb=$(stat -c %s "./tests/test_data/test_results_output/"*"/slamfest_results.txt")
        zip_size_kb=$(stat -c %s "./tests/test_data/test_results_output/"*"/slamfest_results.zip")

        txt_size_kb=$((txt_size_kb / 1024))
        zip_size_kb=$((zip_size_kb / 1024))

        if [ "$txt_size_kb" -ne 28 ]; then
          echo "slamfest_results.txt is not 28KB, it is ${txt_size_kb}KB"
          exit 1
        fi

        if [ "$zip_size_kb" -ne 305 ]; then
          echo "slamfest_results.zip is not 305KB, it is ${zip_size_kb}KB"
          exit 1
        fi