name: WarcSearcher Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run unit tests with coverage
      run: |
        coverage run -m pytest tests/

    - name: Check coverage percentage
      run: |
        coverage report --fail-under=80

  file-operations:
    name: Test WarcSearcher Results
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Initialize test data
      run: |
        test -d "./tests/test_data/test_warc_gz_archives"
        test -d "./tests/test_data/test_regex_definitions"
        test -d "./tests/test_data/test_results_output"
        test -d "./tests/test_data/test_config.ini"

        # Replace the default config.ini with the CI testing one
        rm ./config.ini
        cp ./tests/test_data/test_config.ini ./config.ini
        test -f "./config.ini"

    - name: Run WarcSearcher
      run: |
        set -e
        python source/main.py

    - name: List output folder contents
      run: |
        ls -lhR "./tests/test_data/test_results_output"

    - name: Verify output files exist
      run: |
        test $(find "./tests/test_data/test_results_output" -name "log.log" | wc -l) -gt 0
        test $(find "./tests/test_data/test_results_output" -name "slamfest_results.txt" | wc -l) -gt 0
        test $(find "./tests/test_data/test_results_output" -name "slamfest_results.zip" | wc -l) -gt 0

    - name: Verify output file sizes
      run: |
        txt_size_kb=$(stat -c %s "./tests/test_data/test_results_output/"*"/slamfest_results.txt")
        zip_size_kb=$(stat -c %s "./tests/test_data/test_results_output/"*"/slamfest_results.zip")

        txt_size_kb=$(( (txt_size_kb + 1023) / 1024 ))
        zip_size_kb=$(( (zip_size_kb + 1023) / 1024 ))

        if [ "$txt_size_kb" -ne 28 ]; then
          echo "slamfest_results.txt is not 28KB, it is ${txt_size_kb}KB"
          exit 1
        fi

        if [ "$zip_size_kb" -ne 305 ]; then
          echo "slamfest_results.zip is not 305KB, it is ${zip_size_kb}KB"
          exit 1
        fi