# This workflow will install Python dependencies and run tests with Python 3.13
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Unit Tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run unit tests with coverage
      run: |
        coverage run -m pytest tests/

    - name: Check coverage percentage
      run: |
        coverage report --fail-under=80

    - name: Upload coverage results
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov

    